/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateTodoInput {
  'title' : string,
  'sortOrder' : bigint,
  'dueDate' : [] | [bigint],
  'description' : string,
  'category' : [] | [string],
  'priority' : Priority,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Subtask {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
}
export interface Todo {
  'id' : bigint,
  'title' : string,
  'sortOrder' : bigint,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'category' : [] | [string],
  'priority' : Priority,
  'subtasks' : Array<Subtask>,
}
export interface UpdateTodoInput {
  'id' : bigint,
  'title' : string,
  'sortOrder' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'category' : [] | [string],
  'priority' : Priority,
}
export interface UserPreferences { 'darkMode' : boolean }
export interface _SERVICE {
  'addSubtask' : ActorMethod<[bigint, string], boolean>,
  'createTodo' : ActorMethod<[CreateTodoInput], Todo>,
  'deleteAllCompleted' : ActorMethod<[], bigint>,
  'deleteSubtask' : ActorMethod<[bigint, bigint], boolean>,
  'deleteTodo' : ActorMethod<[bigint], boolean>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getPreferences' : ActorMethod<[], UserPreferences>,
  'getTodos' : ActorMethod<[], Array<Todo>>,
  'markAllCompleted' : ActorMethod<[], undefined>,
  'reorderTodo' : ActorMethod<[bigint, bigint], boolean>,
  'setDarkMode' : ActorMethod<[boolean], undefined>,
  'toggleSubtask' : ActorMethod<[bigint, bigint], boolean>,
  'updateTodo' : ActorMethod<[UpdateTodoInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];