/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const CreateTodoInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});
export const Subtask = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Todo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'priority' : Priority,
  'subtasks' : IDL.Vec(Subtask),
});
export const UserPreferences = IDL.Record({ 'darkMode' : IDL.Bool });
export const UpdateTodoInput = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'addSubtask' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'createTodo' : IDL.Func([CreateTodoInput], [Todo], []),
  'deleteAllCompleted' : IDL.Func([], [IDL.Nat], []),
  'deleteSubtask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'getTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
  'markAllCompleted' : IDL.Func([], [], []),
  'reorderTodo' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'setDarkMode' : IDL.Func([IDL.Bool], [], []),
  'toggleSubtask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateTodo' : IDL.Func([UpdateTodoInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CreateTodoInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  const Subtask = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const Todo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'priority' : Priority,
    'subtasks' : IDL.Vec(Subtask),
  });
  const UserPreferences = IDL.Record({ 'darkMode' : IDL.Bool });
  const UpdateTodoInput = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  
  return IDL.Service({
    'addSubtask' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'createTodo' : IDL.Func([CreateTodoInput], [Todo], []),
    'deleteAllCompleted' : IDL.Func([], [IDL.Nat], []),
    'deleteSubtask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'getTodos' : IDL.Func([], [IDL.Vec(Todo)], ['query']),
    'markAllCompleted' : IDL.Func([], [], []),
    'reorderTodo' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'setDarkMode' : IDL.Func([IDL.Bool], [], []),
    'toggleSubtask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateTodo' : IDL.Func([UpdateTodoInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };