/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subtask {
    id: bigint;
    title: string;
    completed: boolean;
}
export interface UserPreferences {
    darkMode: boolean;
}
export interface UpdateTodoInput {
    id: bigint;
    title: string;
    sortOrder: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
}
export interface Todo {
    id: bigint;
    title: string;
    sortOrder: bigint;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
    subtasks: Array<Subtask>;
}
export interface CreateTodoInput {
    title: string;
    sortOrder: bigint;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    addSubtask(todoId: bigint, title: string): Promise<boolean>;
    createTodo(input: CreateTodoInput): Promise<Todo>;
    deleteAllCompleted(): Promise<bigint>;
    deleteSubtask(todoId: bigint, subtaskId: bigint): Promise<boolean>;
    deleteTodo(id: bigint): Promise<boolean>;
    getCategories(): Promise<Array<string>>;
    getPreferences(): Promise<UserPreferences>;
    getTodos(): Promise<Array<Todo>>;
    markAllCompleted(): Promise<void>;
    reorderTodo(id: bigint, sortOrder: bigint): Promise<boolean>;
    setDarkMode(enabled: boolean): Promise<void>;
    toggleSubtask(todoId: bigint, subtaskId: bigint): Promise<boolean>;
    updateTodo(input: UpdateTodoInput): Promise<boolean>;
}
import type { CreateTodoInput as _CreateTodoInput, Priority as _Priority, Subtask as _Subtask, Todo as _Todo, UpdateTodoInput as _UpdateTodoInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubtask(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubtask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubtask(arg0, arg1);
            return result;
        }
    }
    async createTodo(arg0: CreateTodoInput): Promise<Todo> {
        if (this.processError) {
            try {
                const result = await this.actor.createTodo(to_candid_CreateTodoInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Todo_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTodo(to_candid_CreateTodoInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Todo_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAllCompleted(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllCompleted();
            return result;
        }
    }
    async deleteSubtask(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubtask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubtask(arg0, arg1);
            return result;
        }
    }
    async deleteTodo(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTodo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTodo(arg0);
            return result;
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return result;
        }
    }
    async getTodos(): Promise<Array<Todo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodos();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodos();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllCompleted(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllCompleted();
            return result;
        }
    }
    async reorderTodo(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderTodo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderTodo(arg0, arg1);
            return result;
        }
    }
    async setDarkMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDarkMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDarkMode(arg0);
            return result;
        }
    }
    async toggleSubtask(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSubtask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSubtask(arg0, arg1);
            return result;
        }
    }
    async updateTodo(arg0: UpdateTodoInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTodo(to_candid_UpdateTodoInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTodo(to_candid_UpdateTodoInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Priority_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Todo_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Todo): Todo {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    sortOrder: bigint;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    category: [] | [string];
    priority: _Priority;
    subtasks: Array<_Subtask>;
}): {
    id: bigint;
    title: string;
    sortOrder: bigint;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
    subtasks: Array<Subtask>;
} {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        category: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.category)),
        priority: from_candid_Priority_n9(_uploadFile, _downloadFile, value.priority),
        subtasks: value.subtasks
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Todo>): Array<Todo> {
    return value.map((x)=>from_candid_Todo_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateTodoInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTodoInput): _CreateTodoInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTodoInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTodoInput): _UpdateTodoInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    sortOrder: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
}): {
    id: bigint;
    title: string;
    sortOrder: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    category: [] | [string];
    priority: _Priority;
} {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        category: value.category ? candid_some(value.category) : candid_none(),
        priority: to_candid_Priority_n3(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    sortOrder: bigint;
    dueDate?: bigint;
    description: string;
    category?: string;
    priority: Priority;
}): {
    title: string;
    sortOrder: bigint;
    dueDate: [] | [bigint];
    description: string;
    category: [] | [string];
    priority: _Priority;
} {
    return {
        title: value.title,
        sortOrder: value.sortOrder,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        category: value.category ? candid_some(value.category) : candid_none(),
        priority: to_candid_Priority_n3(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
